### ISSUE TITLE
Register allows user to create account without checking privacy policy checkbox.

### ISSUE THREAD

**Issue by ujwalkumar1995** [faridhashimov/ecommerce-store#2]
On the registration screen, user is able to create an account without checking the terms and conditions checkbox.

Expected Behaviour:
Sign up button should be disabled if user has not checked the privacy policy checkbox.

![Screenshot_20230221_064334](https://user-images.githubusercontent.com/20976813/220354476-ef643171-9de7-41b5-bd7f-dc5d665d8c5d.png)

**Comment by faridhashimov** [comment]
Add new feature for privacy policy checking, Sign Up button disabled unless we checkbox checked.
